name: Sync to Pro Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4
        with:
          repository: 'BDenizKoca/tideflow'
          fetch-depth: 0 # Important: fetch all history for all branches and tags
          
      - name: Mirror to Private Repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: 'https://x-access-token:${{ secrets.GH_PAT }}@github.com/BDenizKoca/Tideflow-Pro.git'
          push_options: '--mirror'
